name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build
        env:
          BASE_URL: https://fawadali.dev/
        run: |
          yarn install --silent
          yarn build --base=$BASE_URL

      - name: Embed Google Tag Manager Code
        if: ${{ vars.GTM_EMBED_CODE }}
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: '<!-- {GTM_EMBED_CODE_PLACEHOLDER} -->'
          replace: '${{ vars.GTM_EMBED_CODE }}'
          regex: false
          include: 'dist/index.html'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          commit_message: ${{ github.event.head_commit.message }}
          cname: fawadali.dev
